# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='TranscodeTask.proto',
  package='',
  serialized_pb='\n\x13TranscodeTask.proto\"\xb3\x01\n\rTranscodeTask\x12\x0b\n\x03tid\x18\x01 \x02(\x05\x12\x11\n\tinputName\x18\x02 \x02(\t\x12\x12\n\ncommonPath\x18\x03 \x01(\t\x12\x11\n\tinputPath\x18\x04 \x01(\t\x12\x11\n\tinputHash\x18\x05 \x01(\t\x12\x0b\n\x03\x61rt\x18\x06 \x01(\x0c\x12\x0f\n\x07\x61rtHash\x18\x07 \x01(\t\x12\x0f\n\x07\x61rtName\x18\x08 \x01(\t\x12\x19\n\x11partOfCompilation\x18\t \x01(\x08')




_TRANSCODETASK = descriptor.Descriptor(
  name='TranscodeTask',
  full_name='TranscodeTask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='tid', full_name='TranscodeTask.tid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='inputName', full_name='TranscodeTask.inputName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='commonPath', full_name='TranscodeTask.commonPath', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='inputPath', full_name='TranscodeTask.inputPath', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='inputHash', full_name='TranscodeTask.inputHash', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='art', full_name='TranscodeTask.art', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='artHash', full_name='TranscodeTask.artHash', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='artName', full_name='TranscodeTask.artName', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='partOfCompilation', full_name='TranscodeTask.partOfCompilation', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=24,
  serialized_end=203,
)



class TranscodeTask(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRANSCODETASK
  
  # @@protoc_insertion_point(class_scope:TranscodeTask)

# @@protoc_insertion_point(module_scope)
